# Generated by Django 6.0.4 on 2026-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_id', models.CharField(blank=True, help_text='ID de AnimeNewsNetwork', max_length=50, null=True, unique=True)),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True)),
                ('url_externa', models.URLField(blank=True)),
                ('imagen_url', models.URLField(blank=True)),
                ('tipo', models.CharField(choices=[('news', 'Noticia'), ('review', 'Review'), ('release', 'Lanzamiento'), ('event', 'Evento')], default='news', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
