# Generated by Django 6.0.4 on 2026-04-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='updated_at',
            new_name='sincronizado_en',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha_ann',
            field=models.CharField(blank=True, help_text='Año/temporada de emisión según ANN', max_length=20),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='ann_id',
            field=models.CharField(default='0', help_text='ID del título en ANN', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='tipo',
            field=models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga')], default='anime', max_length=10),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url_externa',
            field=models.URLField(help_text='Enlace a la Encyclopedia de ANN (obligatorio por sus ToS)'),
        ),
    ]
