# Generated by Django 6.0.4 on 2026-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(blank=True, help_text='Cuerpo completo del artículo extraído de ANN'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='ann_id',
            field=models.CharField(help_text='ID único generado desde la URL del artículo RSS', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Introducción del artículo (del RSS)'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_ann',
            field=models.CharField(blank=True, help_text='Fecha de publicación según ANN', max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url_externa',
            field=models.URLField(help_text='Enlace al artículo original de ANN (obligatorio por sus ToS)'),
        ),
    ]
