# Generated by Django 6.0.4 on 2026-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_noticia_contenido_alter_noticia_ann_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='contenido_es',
            field=models.TextField(blank=True, help_text='Cuerpo traducido al español por MyMemory'),
        ),
    ]
