# Generated by Django 6.0.4 on 2026-04-17 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('titulo_japones', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('estudio', models.CharField(blank=True, max_length=200)),
                ('anio_emision', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('airing', 'En emisión'), ('finished', 'Finalizado'), ('upcoming', 'Próximamente'), ('cancelled', 'Cancelado')], default='airing', max_length=20)),
                ('tipo', models.CharField(choices=[('tv', 'Serie TV'), ('movie', 'Película'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'Especial')], default='tv', max_length=10)),
                ('total_episodios', models.PositiveIntegerField(blank=True, null=True)),
                ('portada_url', models.URLField(blank=True)),
                ('portada_local', models.ImageField(blank=True, null=True, upload_to='Portadas/Anime/')),
                ('destacado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generos', models.ManyToManyField(blank=True, related_name='animes', to='anime.genero')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangadex_id', models.CharField(blank=True, help_text='UUID de MangaDex para obtener portada e info', max_length=255)),
                ('titulo', models.CharField(max_length=300)),
                ('titulo_original', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('anio_publicacion', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ongoing', 'En curso'), ('completed', 'Completado'), ('hiatus', 'En hiato'), ('cancelled', 'Cancelado')], default='ongoing', max_length=20)),
                ('portada_url', models.URLField(blank=True, help_text='URL externa de la portada (MangaDex)')),
                ('portada_local', models.ImageField(blank=True, null=True, upload_to='Portadas/Manga/')),
                ('destacado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generos', models.ManyToManyField(blank=True, related_name='mangas', to='anime.genero')),
            ],
            options={
                'verbose_name': 'Manga',
                'verbose_name_plural': 'Mangas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=1, help_text='Ej: 1, 7.5, 100', max_digits=6)),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('volumen', models.PositiveIntegerField(blank=True, null=True)),
                ('ruta_imagenes', models.CharField(blank=True, max_length=500)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='anime.manga')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now=True)),
                ('completado', models.BooleanField(default=False)),
                ('pagina_actual', models.PositiveIntegerField(default=1)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='anime.capitulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('duracion_min', models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Episodio',
                'verbose_name_plural': 'Episodios',
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('anime', 'numero'), name='unique_episodio_anime')],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manga', 'Manga'), ('anime', 'Anime')], max_length=10)),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('nota_personal', models.TextField(blank=True)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='anime.anime')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='anime.manga')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('manga__isnull', False)), fields=('usuario', 'manga'), name='unique_favorito_manga'), models.UniqueConstraint(condition=models.Q(('anime__isnull', False)), fields=('usuario', 'anime'), name='unique_favorito_anime')],
            },
        ),
        migrations.AddConstraint(
            model_name='capitulo',
            constraint=models.UniqueConstraint(fields=('manga', 'numero'), name='unique_capitulo_manga'),
        ),
        migrations.AddConstraint(
            model_name='progreso',
            constraint=models.UniqueConstraint(fields=('usuario', 'capitulo'), name='unique_progreso_capitulo'),
        ),
    ]
