# Generated by Django 6.0.4 on 2026-05-17 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='generos',
        ),
        migrations.RemoveConstraint(
            model_name='episodio',
            name='unique_episodio_anime',
        ),
        migrations.RemoveConstraint(
            model_name='favorito',
            name='unique_favorito_manga',
        ),
        migrations.RemoveConstraint(
            model_name='favorito',
            name='unique_favorito_anime',
        ),
        migrations.AlterField(
            model_name='favorito',
            name='manga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='anime.manga'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'manga'), name='unique_favorito_manga'),
        ),
        migrations.AlterModelTable(
            name='capitulo',
            table='capitulos',
        ),
        migrations.AlterModelTable(
            name='favorito',
            table='favoritos',
        ),
        migrations.AlterModelTable(
            name='genero',
            table='generos',
        ),
        migrations.AlterModelTable(
            name='manga',
            table='mangas',
        ),
        migrations.AlterModelTable(
            name='progreso',
            table='progresos',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Episodio',
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
