# Generated by Django 6.0.4 on 2026-05-20 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_generos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='mangadex_id',
            field=models.CharField(blank=True, help_text='ID externo del manga', max_length=255),
        ),
        migrations.AlterField(
            model_name='manga',
            name='portada_url',
            field=models.URLField(blank=True, help_text='URL rápida de la portada elegida'),
        ),
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField(max_length=1000)),
                ('titulo_busqueda', models.CharField(blank=True, max_length=300)),
                ('fuente', models.CharField(default='nekosapi', max_length=50)),
                ('es_principal', models.BooleanField(default=False)),
                ('creada_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portadas', to='anime.manga')),
            ],
            options={
                'verbose_name': 'Portada',
                'verbose_name_plural': 'Portadas',
                'db_table': 'portadas',
                'ordering': ['-es_principal', '-creada_at'],
            },
        ),
    ]
