# Generated by Django 6.0.4 on 2026-05-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_manga_mangadex_id_alter_manga_portada_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portada',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='portada',
            name='imagen',
            field=models.ImageField(default=1, upload_to='portadas/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portada',
            name='fuente',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AlterModelTable(
            name='portada',
            table=None,
        ),
    ]
